package utils

var Symbols = map[string]string{
	"error":        "❌",
	"noAction":     "❎",
	"home":         "⛺",
	"upVote":       "👍",
	"downVote":     "👎",
	"upArrow":      "⬆️",
	"downArrow":    "⬇️",
	"calendar":     "📅",
	"comment":      "💬",
	"tag":          "🏷t",
	"text":         "📝",
	"spark":        "⚡",
	"checkerdFlag": "🏁",
	"redFlag":      "🚩",
	"clock":        "⏰",
	"done":         "✅",
	"search":       "🔎",
	"clip":         "🔗",
	"pad":          "📋",
	"add":          "➕",
	"backup":       "💾",
}
