package utils

var Symbols = map[string]string{
	"add":          "➕",
	"backup":       "💾",
	"calendar":     "📅",
	"checkerdFlag": "🏁",
	"clip":         "🔗",
	"clock":        "⏰",
	"comment":      "💬",
	"done":         "✅",
	"downArrow":    "⬇️",
	"downVote":     "👎",
	"error":        "❌",
	"glossary":     "📖",
	"hat":          "🎩",
	"home":         "⛺",
	"noAction":     "❎",
	"pad":          "📋",
	"redFlag":      "🚩",
	"refresh":      "🔄",
	"search":       "🔎",
	"spark":        "⚡",
	"tag":          "🏷t",
	"telescope":    "🔭",
	"text":         "📝",
	"think":        "🤔",
	"upArrow":      "⬆️",
	"upVote":       "👍",
	"warning":      "⚠️ ",
	"zzz":          "💤",
}
