package utils

var Symbols = map[string]string{
	"error":         "❌",
	"no_action":     "❎",
	"home":          "⛺",
	"up_vote":       "👍",
	"down_vote":     "👎",
	"up_arrow":      "⬆️",
	"down_arrow":    "⬇️",
	"calendar":      "📅",
	"comment":       "💬",
	"tag":           "🏷t",
	"text":          "📝",
	"spark":         "⚡",
	"checkerd_flag": "🏁",
	"red_flag":      "🚩",
	"clock":         "⏰",
	"done":          "✅",
	"search":        "🔎",
	"clip":          "🔗",
	"pad":           "📋",
	"add":           "➕",
	"backup":        "💾",
}
