appinfo:
  data_file: ~/reminder/data.json
log:
  level: 5
  lookup_fields:
  - app
  - run_id
calendar:
  credential_file: ~/calendar_credentials.json
  token_file: ~/calendar_token.json
  dry_mode: false
