# The `default.yaml` is just representation of default settings. It is not used
# in the code.
# For desired settings, create `current.yaml` file and use if for keeping
# the current operational values.

appinfo:
  data_file: ~/reminder/data.json
log:
  level: 5
  lookup_fields:
  - app
  - run_id
calendar:
  credential_file: ~/calendar_credentials.json
  token_file: ~/calendar_token.json
  dry_mode: false
