# refer: https://github.com/goreleaser/goreleaser
# refer: https://goreleaser.com/
name: ci

on:
  push:
    branches:
      - '*'

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: '>=1.21.0'
      - name: Build
        run: make gobuild
      - name: Check Lint
        run: make lint
      - name: Test
        run: CI=true CONSOLE_PRINT=true make test
